services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v8.12.7
    network_mode: service:ts-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    mem_limit: 128m

  ts-dozzle:
    image: tailscale/tailscale:latest
    container_name: ts-dozzle
    hostname: dozzle-hypatia
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=${TS_AUTHKEY:?error}
      - TS_EXTRA_ARGS=--reset
      - TS_SERVE_CONFIG=/config/dozzle.json
      - TS_USERSPACE=false
    volumes:
      - ./dozzle.json:/config/dozzle.json
      - ts-dozzle:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    mem_limit: 200m

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    platform: linux/arm64
    restart: unless-stopped
    privileged: true
    network_mode: service:ts-glances
    depends_on:
      - ts-glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w -t 5
      - PUID=0
      - PGID=0
      - TZ=Europe/Amsterdam
    mem_limit: 512m

  ts-glances:
    image: tailscale/tailscale:latest
    container_name: ts-glances
    hostname: glances-hypatia
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=${TS_AUTHKEY:?error}
      - TS_EXTRA_ARGS=--reset
      - TS_SERVE_CONFIG=/config/glances.json
      - TS_USERSPACE=false
    volumes:
      - ./glances.json:/config/glances.json
      - ts-glances:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    mem_limit: 200m

volumes:
  ts-dozzle:
  ts-glances:
